language: ruby
rvm:
  - 2.1.2
install: 
  - gem install mail
  - gem install json
  - gem install rest-client
  - gem install rake
  - gem install minitest-spec
  - gem install minitest-reporters
  - gem install minitest-spec-context
  - gem install mock_redis
sudo: required
